version: '3.8'

services:
  taskboard:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:taskboard
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      - h2
    networks:
      - taskboard-network

  h2:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-web -webAllowOthers -webPort 8082
    volumes:
      - h2-data:/opt/h2-data
    networks:
      - taskboard-network

volumes:
  h2-data:

networks:
  taskboard-network: